server:
  port:
    9090


spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dbybook
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 333333
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
    host: redis
    database: 3
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0


mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: top.cuizilin.dby.pojo
  configuration:
    map-underscore-to-camel-case: true